### ISSUE TITLE
橡皮擦线宽的问题

### ISSUE THREAD

**Issue by coderchou** [HaydenYe/HYWhiteboard#1]
```
// 渲染橡皮画线
- (void)_drawEraserPoint:(CGPoint)point lineWidth:(CGFloat)width {
    CGFloat lineWidth = width * 2.f / 1.414f;
    
    // 只重绘局部，提高效率
    CGRect brushRect = CGRectMake(point.x - lineWidth /2.f, point.y - lineWidth/2.f, lineWidth, lineWidth);
    [self.layer setNeedsDisplayInRect:brushRect];
    
    // 十分关键，需要立即渲染
    [self.layer display];
}

```
上面的方法中，lineWidth = width * 2.f / 1.414f 原理是什么，在iOS 11的系统下， brushRect 与 擦除的实际范围不一致，没有找到有效的解决方法，请帮我看下问题

**Comment by HaydenYe** [comment]
橡皮擦的线宽确实会有误差，因为是用正方形模拟画线，所以与贝塞尔曲线的线宽存在误差，比如，在用在用正方形画直线时，线宽就是正方形的边长，也是贝塞尔曲线的线宽；但是在画45度斜线的时候，贝塞尔的线宽其实应该是正方形的对角线长，所以会有误差

**Comment by coderchou** [comment]
非常感谢大神的回复，深层次的原理我搞不懂。
这个画板功能非常好用，特别是解决了存在背景的情况下，橡皮擦的实现，iOS 12以上非常完美。
再次感谢作者！

**Comment by HaydenYe** [comment]
iOS12以上非常完美是因为，橡皮擦使用的是贝塞尔曲线完成的，并没有经过优化，当已经画了很多线的时候，再使用橡皮擦会非常卡顿。而iOS12以下会使用脏矩形进行模拟画线，优化卡顿的问题，虽然线宽会有些误差，但是不影响使用和用户体验，如果方便的话，可以告知一下您的使用场景是什么？需要严格的橡皮擦线宽？一般来讲，直接写死橡皮擦的宽度都是可以接受的

**Comment by coderchou** [comment]
目前开发的这个app是提供给老师课堂教学使用。app具备投屏功能，手机界面投屏到大屏上，老师打开app中的画板功能，给学生讲解题目，大致就是这样一个需求。
iOS 橡皮檫真的不简单，还好有大神写的这个库，谢谢！

**Comment by HaydenYe** [comment]
你可以将CGFloat lineWidth = width * 2.f / 1.414f;去掉，直接CGFloat lineWidth = 5.f 这样写几个固定值，测试一下是否在iOS11可以满足产品需求，如果还是不能接受这种误差，可以选择关闭iOS12以下的这个橡皮擦优化，直接使用贝塞尔曲线，但是画线过多会很卡。
关闭橡皮擦优化可以从下面这个方法里面稍微调整下判断就好
// 橡皮直接渲染到视图
- (void)drawEraserLineByPoint:(HYWbPoint *)wbPoint

**Comment by HaydenYe** [comment]
你可以将CGFloat lineWidth = width * 2.f / 1.414f;去掉，直接CGFloat lineWidth = 5.f 这样写几个固定值，测试一下是否在iOS11可以满足产品需求，如果还是不能接受这种误差，可以选择关闭iOS12以下的这个橡皮擦优化，直接使用贝塞尔曲线，但是画线过多会很卡。
关闭橡皮擦优化可以从下面这个方法里面稍微调整下判断就好
// 橡皮直接渲染到视图
- (void)drawEraserLineByPoint:(HYWbPoint *)wbPoint

**Comment by coderchou** [comment]
好的，非常感谢解答！
